### ISSUE TITLE
EPIC: Debug and fix current issues with no longer working features

### ISSUE THREAD

**Issue by GoetzGoerisch** [umati/Dashboard-OPCUA-Client#537]
Debug and fix issues.

Related:

- [x] umati/Dashboard-OPCUA-Client#535 
- [ ] umati/Dashboard-OPCUA-Client#501 
- [x] umati/Dashboard-OPCUA-Client#497 
- [x] umati/Dashboard-OPCUA-Client#483 
- [x] umati/Dashboard-OPCUA-Client#454 
- [x] umati/Dashboard-OPCUA-Client#361

**Comment by DasbachVDMA** [comment]
Probably won't fix, in favor of the new gateway.
